### PR TITLE
recognise MicrosoftWebDriver 17134

### PR DESCRIPTION
**Pull request by dten**
allow edge webdriver 17134 to be recognised as valid version

### CODE REVIEW

**Comment by amit1980in** [comment]
I tried your fix with web component tester and it didn't worked. I am still getting following error
Error: The following browsers were not found: edge. (All installed browsers found: chrome, ie)

I am trying this on windows 10 with OS version 17134

**Comment by dten** [comment]
What did you try? Works for me when I use a custom config to install / start selenium standalone

**Comment by amit1980in** [comment]
I am using web component tester to test my component written in polymer against edge browser. it works fine with edge browser 16.16299 but not with edge version 17.17134. My understanding is that web component internally use selenium to run test cases against specific web driver version. I tried running WCT command after I added edge version 17.17134 in microsoft-edge-releases.js file and I am getting below error while running wct command.

Error: The following browsers were not found: edge. (All installed browsers found: chrome, ie)

**Comment by dten** [comment]
You'll want to change the default config also to make it use this version

https://github.com/vvo/selenium-standalone/blob/master/lib/default-config.js

Or use a custom config

**Comment by amit1980in** [comment]
I changed default-config.js to point edge: {
      version: '17134'
    }
 but still I am getting below errror
Error: The following browsers were not found: edge. (All installed browsers found: chrome, ie)

**Comment by amit1980in** [comment]
I would like to run rest against 17.17134 edge browser because this is what comes with windows 10 latest update. Please advise if selenium support it.

**Comment by amit1980in** [comment]
Hi
Just wanted to inform you that I am able to launch edge browser 17.17134 after I restarted PC.

Thanks for your help.

Regards
Amit

**Pull request merged**
