### PR TITLE
Update geckodriver to 0.10.0

### PR DESCRIPTION
**Pull request by nolanlawson**
There's a new release of geckodriver out.

### CODE REVIEW

**Comment by patthiel** [comment]
There's also a new chromedriver out (2.23). Perhaps we can update both in this PR? The version will need to be bumped for chromedriver in default-config and in `lib/compute-download-urls.js` line 59 needs to be updated to `mac64.

cc @vvo

**Comment by vvo** [comment]
Will update both, @nolanlawson you are now a contributor here and on npm for selenium-standalone so you can release :)

**Comment by vvo** [comment]
I will release that one

**Comment by vvo** [comment]
@patthiel Feel free to submit PRS next time, thanks for the notification about mac64

**Comment by nolanlawson** [comment]
Cheers, thanks for the release!

**Pull request merged**
