### PR TITLE
Update for lastest version of Selenium and Geckodriver

### PR DESCRIPTION
**Pull request by geskill**
Changelogs:
- [Selenium](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG)
- [Internet Explorer](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/cpp/iedriverserver/CHANGELOG)
- [Geckodriver](https://github.com/mozilla/geckodriver/releases/tag/v0.16.0)

### CODE REVIEW

**Comment by vvo** [comment]
👌 , no idea if this will break everything as usual, should we bump major?

**Comment by geskill** [comment]
i wouldn't since 6.x comes with selenium 3.x already.

_remark:
This update fixes issues with Firefox, in order to work with FF 47+ (thats at least what i experienced). Before i had issues using any FF version in selenium 3. Therefore i used selenium 2 and FF 47._

**Comment by geskill** [comment]
Currently, the Actions API is not completely supported by Geckodriver  https://github.com/mozilla/geckodriver/issues/159

**Comment by vvo** [comment]
> Currently, the Actions API is not completely supported by Geckodriver mozilla/geckodriver#159

Does it means we need to do something different in term of versionning?

**Comment by geskill** [comment]
No, because this update is an improvement, although there is this unimplemented feature. Before there is no conf (i know) that allow us to use FF with Selenium 3.x

**Pull request merged**
