### PR TITLE
Lastest version of Chrome driver

### PR DESCRIPTION
**Pull request by Goye**
Updated default value for Chrome driver version

### CODE REVIEW

**Comment by vvo** [comment]
Will this work? Since it also need to handle mac64 download no? has you said

**Comment by Goye** [comment]
k, let me see how to handle it :)

**Comment by Goye** [comment]
@vvo sorry I was checking the issue and it was a problem with my version.

because in the 5.5.0 - computer-download-urls - line 25 you don't have a validation for that but in the 5.6.3, same file - line 28 you added: 

`if (opts.drivers.chrome.version < 2.23) {
     mac32 = true;
 }`  

so it's fixed right now

**Comment by stephenash** [comment]
@Goye Sounds like everything is good then. If that is correct, can this PR and https://github.com/vvo/selenium-standalone/issues/220 be closed?

**Comment by Goye** [comment]
@stephenash Yeah but with this PR I just updated the default version to the latest

**Comment by vvo** [comment]
Not sure to follow, do we need to merge this to still default to 2.34?

**Comment by Goye** [comment]
@vvo yep

**Pull request merged**
