### PR TITLE
Support custom binaries download url

### PR DESCRIPTION
**Pull request by fengmk2**
Fixes https://github.com/cnpm/cnpmjs.org/issues/566

### CODE REVIEW

**Comment by vvo** [comment]
I will have a look today to see how I can plug this in the programmatic API with options rather than env variables, you will access it by flags on the command line, enough? @fengmk2

**Comment by fengmk2** [comment]
yep, enough for me.

**Comment by fengmk2** [comment]
@vvo any suggestions?

**Comment by vvo** [comment]
@fengmk2 see https://github.com/vvo/selenium-standalone/blob/master/HISTORY.md#320-2015-01-23

enough?

**Comment by fengmk2** [comment]
@vvo thanks! Your is better.

**Pull request closed without merging**
