### PR TITLE
expectedRequests should be 4 after firefox driver

### PR DESCRIPTION
**Pull request by azakus**
selenium itself, ie, chrome, firefox

### CODE REVIEW

**Comment by garlicnation** [comment]
Context:

This change: https://github.com/vvo/selenium-standalone/pull/187

Causes failures like this: https://travis-ci.org/PolymerElements/iron-demo-helpers/builds/142869473

**Comment by vvo** [comment]
LGTM

**Comment by vvo** [comment]
@azakus you are now a contributor on this

**Comment by vvo** [comment]
on npm also

**Comment by vvo** [comment]
released as 5.4.1

**Pull request merged**
