### PR TITLE
Allow passing java command line arguments (-D like) to be included be…

### PR DESCRIPTION
**Pull request by marcelofarias**
…fore -jar

### CODE REVIEW

**Comment by vvo** [comment]
Hey Hi! Can you provide me a bit more context on what you are fixing and why the current situation did not allow it?

Thanks!

**Comment by marcelofarias** [comment]
System properties (like -Djava.util.logging.config.file=logging.properties,
for instance), have to be specified in the command line *before* the jar
name (they are arguments to java, not to the jar entry point).

So, the two command lines below are *not* equivalent

java -Djava.util.logging.config.file=logging.properties -jar selenium.jar #
this one works
java -jar selenium.jar -Djava.util.logging.config.file=logging.properties #
this one doesn't

Summing up: java arguments have to be included *before* the -jar jarname.jar
in the command line.

That's why you recently fixed this:
https://github.com/vvo/selenium-standalone/commit/768aac81b69d89ef30af6a341110d78ef4541337

Use case:

selenium.start({
    javaArgs = [ -Djava.util.logging.config.file=logging.properties ],
    seleniumArgs = [ '-port', '4450' ]
}, callback);



*Marcelo Bukowski de Farias*
Software Engineer, Sencha Test
Office: +1-650-299-9550 <1-650-299-9550>
<http://www.facebook.com/senchainc> <http://twitter.com/sencha>
<https://www.linkedin.com/company/sencha-inc>
<http://www.youtube.com/SenchaInc>
<https://plus.google.com/117303203295549187007?prsrc=3>
[image: SenchaCon 2016 Aria Resort, Las Vegas, November 7-9]
<https://www.senchacon.com/>
*Join me at SenchaCon 2016!*

**Comment by marcelofarias** [comment]
System properties (like ```-Djava.util.logging.config.file=logging.properties```,
for instance), have to be specified in the command line *before* the jar
name (they are arguments to java, not to the jar entry point).

So, the two command lines below are *not* equivalent

```
java -Djava.util.logging.config.file=logging.properties -jar selenium.jar #
this one works
java -jar selenium.jar -Djava.util.logging.config.file=logging.properties #
this one doesn't
```

Summing up: java arguments have to be included *before* the ```-jar jarname.jar```
in the command line.

That's why you recently fixed this:
https://github.com/vvo/selenium-standalone/commit/768aac81b69d89ef30af6a341110d78ef4541337

Use case:

```
selenium.start({
    javaArgs = [ -Djava.util.logging.config.file=logging.properties ],
    seleniumArgs = [ '-port', '4450' ]
}, callback);
```

**Comment by jucrouzet** [comment]
LGTM :+1: 
Could also be useful for the -Xmx / -Xms in case of  `java.lang.OutOfMemoryError` (big returned object, etc.)

**Comment by marcelofarias** [comment]
@jucrouzet Just updated README.md

**Comment by vvo** [comment]
Thanks this can be merged and published!

**Comment by marcelofarias** [comment]
@vvo @jucrouzet any chance to press the green button of glory?

**Pull request merged**
