### PR TITLE
update Selenium and Geckodriver versions

### PR DESCRIPTION
**Pull request by axelhildingson**
Update version to the latest version

Reason
Latest gecko is dependent on latest selenium driver. The 32-bit linux version of Geckodriver 0.15.0 is missing. See: https://github.com/mozilla/geckodriver/releases.

### CODE REVIEW

**Comment by axelhildingson** [comment]
Can someone rebuild this PR ?, the test shouldn't fail

**Comment by jucrouzet** [comment]
I restarted the job, it was a timeout issue (probably a network / hosting hickup while testing)

**Comment by axelhildingson** [comment]
I thought so too,
do we have any comments on the PR ? I can't see any reason to not merge it.

**Comment by axelhildingson** [comment]
@stephenash

**Comment by axelhildingson** [comment]
ping

**Comment by vvo** [comment]
@axelhildingson Will the 32 bits linux version of gecko be back at some point?

**Pull request merged**
