### PR TITLE
Fix chromiumedge privileges

### PR DESCRIPTION
**Pull request by mgrybyk**
`chmod` is not executed for `chromiumedge`, the PR fixes that.

### CODE REVIEW

**Comment by mgrybyk** [comment]
@vvo can you please review? The issue blocks running tests in the pipeline.
Thanks!

**Comment by vvo** [comment]
Thanks!

(releasing now)

PS: if you're familiar or willing to be familiar with selenium-standalone codebase, I am welcoming maintainers (= reviews, feature, releases..). Because I am no more using this module myself.

**Comment by mgrybyk** [comment]
I'm using it as a part of webdriverio. I can review PRs whenever I have time

**Comment by vvo** [comment]
Released and added you as maintainer (GitHub, npm)

**Comment by vvo** [comment]
@mgrybyk I see you're doing a lot of autumn issues cleaning, thanks A LOT!

BTW, do you have a docker hub account? https://hub.docker.com/ If not, do create one and send me your docker ID. When releasing new versions of selenium-standalone, you will need to be logged in to the docker hub, to push docker images of selenium-standalone, somehow.. :D

**Comment by mgrybyk** [comment]
It's atools https://hub.docker.com/repository/docker/atools

But I can create another one if needed

**Comment by mgrybyk** [comment]
I didn't know we publish docker images

**Comment by vvo** [comment]
@mgrybyk yes you can do that, adding you to docker

**Pull request merged**
