### PR TITLE
Support for node.js 0.10.x

### LINKED ISSUE #156: Add "engines" flag to package.json warning about Node 0.10 incompatibility
This commit, https://github.com/vvo/selenium-standalone/commit/3d6525a65a0879577f41014465e33990e56a7459, breaks Node 0.10 compatibility as `fs.access` is new in 0.12.

It would be very helpful to set the `engines` flag in `package.json` to alert to this incompatibility:
https://docs.npmjs.com/files/package.json#engines

### PR DESCRIPTION
**Pull request by Sanjo**
Closes #156.

### CODE REVIEW

**Comment by vvo** [comment]
nice! why not use https://github.com/sindresorhus/fs-access? I think the check before doing a chmod was necessary

**Comment by vvo** [comment]
https://github.com/vvo/selenium-standalone/pull/150

**Comment by Sanjo** [comment]
Because it doesn't support the access flags that are used. Only F_OK is supported by the package. That's stated on the bottom of the readme.

**Comment by Sanjo** [comment]
Ping :-)

**Comment by vvo** [comment]
Merging, thx

**Comment by vvo** [comment]
will be released as 4.9.1, thanks

**Pull request merged**
