### PR TITLE
#202: Add support for classPath and update readme

### PR DESCRIPTION
**Pull request by joelwatson**
Suggested update for: https://github.com/vvo/selenium-standalone/issues/202

### CODE REVIEW

**Comment by vvo** [comment]
Hi @joelwatson thanks for that!

I am wondering though: given the comment here https://github.com/vvo/selenium-standalone/issues/202#issuecomment-238744407 it seems that the user made it work by using the `-- -cp..`.

Is your PR solving something different? Can you give me more context? Thanks

**Comment by joelwatson** [comment]
Out of the box, I don't believe you can start it successfully with servets (or custom proxies) by providing *both* the -jar and the -cp; I believe it has to be either/or.

**Comment by vvo** [comment]
@joelwatson Can you try it somehow before we include this code, just in case we might be adding some code that is not needed.

I just want to be sure/have proofs that we need this code.

**Comment by vvo** [comment]
reopen if more comments

**Pull request closed without merging**
