### PR TITLE
Added empty handlers to stdout and stderr to fix issue #83.

### PR DESCRIPTION
**Pull request by Robinfr**
The issue is gone with this fix.

### CODE REVIEW

**Comment by vvo** [comment]
AWESOME

**Comment by vvo** [comment]
I am releasing a new version of this right now, awesome find @Robinfr Thanks a lot!

**Comment by vvo** [comment]
`npm install selenium-standalone@4.2.1`

**Comment by Robinfr** [comment]
Thanks!

**Pull request merged**
