### PR TITLE
Fix for issue #104:

### PR DESCRIPTION
**Pull request by binarykitchen**
- Do not callback twice when process already exists
- Error message more clear
- Bump some packages

### CODE REVIEW

**Comment by vvo** [comment]
Good, could you only include the necessary code change without any stylistic, formatting change?

Also, no need to move the export.

Thanks

**Comment by binarykitchen** [comment]
well, i do not support these styles but have reverted that for you - otherwise all good. thanks for merging.

**Comment by vvo** [comment]
The more I think about it the more I thinkg that we should throw/error in the case a selenium server is already running.

Otherwise this selenium instance would be unusable right?

**Comment by binarykitchen** [comment]
No @vvo, the instance can be then reused right away - works fine from my gulp task. It is usable when already run. No need to throw an error.

**Comment by vvo** [comment]
so you have a running selenium you start another one but then you still use the first instance?

**Comment by binarykitchen** [comment]
no - that gulp task is a mocha test runner. sometimes it crashes when an error occurs and doesn't shut down selenium at all. then, imagine this: i fix the code and want to run the mocha tests again and then it complains that selenium is already running. in that case i have to `kill -9` the selenium process form the console and start the gulp task again.

that's why the above patch of mine will help and make it a bit easier for the developer. throwing an error doesn't help and makes it probably worse.

**Comment by vvo** [comment]
> sometimes it crashes when an error occurs and doesn't shut down selenium at all.

so this is the real issue then?

**Comment by vvo** [comment]
if that's fixable

**Comment by binarykitchen** [comment]
there is no issue with my scenario, it's justified when the other gulp task crashes - it can happen and is not related to this issue. all i am saying is that the selenium child process is still running and not cleaned up which can happen in my scenario.

**Comment by vvo** [comment]
4.4.3

**Pull request merged**
