### PR TITLE
Update default chromedriver to 2.39

### PR DESCRIPTION
**Pull request by UsainBloot**
Chromium [released chromedriver 2.39](https://sites.google.com/a/chromium.org/chromedriver/downloads)

This increases support for stable and beta builds of Chrome (v67 & v68)

Binaries available here:
https://chromedriver.storage.googleapis.com/index.html?path=2.31/

### CODE REVIEW

**Comment by serbanghita** [comment]
@vvo I think this can easily be incremented to 2.40 http://chromedriver.chromium.org/downloads

This is important because apparently they fixed `Fixed Minimize/Maximize window need a w3c compliant endpoints`

**Comment by UsainBloot** [comment]
@serbanghita this was the latest when the PR was raised 😆

**Comment by serbanghita** [comment]
@UsainBloot I know 👍 good job!

**Comment by vvo** [comment]
can you update this PR given previously merged ones? cc @serbanghita

**Pull request merged**
