### PR TITLE
fixes #304 - added timeout option to request

### LINKED ISSUE #304: install should timeout after x seconds
## Expected Behavior

I'm currently on a train and try to debug a selenium test. I run `install`, but because of some connection problem the `install` will run forever. It would be nice to have a default timeout (maybe after 10 seconds?), so a real error is thrown. It took me a while to figure out that the `install` runs forever and not some other part of my test.

## Current Behavior

Currently `install` runs forever on a (flaky?) connection.

## Steps to Reproduce

Hard to reproduce. But I can try ;)

- Visit Germany. 🍺 
- Go on a train trip from Munich to Leipzig. 🚋 
- Train should be an ICE. 🚅 
- Log into `WIFIonICE` to get free internet. 📶 
- (Oh, I'm also on corporate VPN for some extra fun. 💃 )
- Run `install`. 🎉 

😄

### PR DESCRIPTION
**Pull request by donaldpipowitch**
Not tested thoroughly (hard for me to reproduce, too), but it looks like I just need to configure `request`? Should fix #304

### CODE REVIEW

**Comment by jucrouzet** [comment]
Fixing an arbitrary timeout of 10s may be a blocking change for people under a slow connection, IMHO, it needs to be configurable.
For the unit tests, you can set a proxy (https://github.com/nodejitsu/node-http-proxy for example) with a delay on the response.

**Comment by donaldpipowitch** [comment]
> it needs to be configurable.

Do you want to just make `timeout` configurable or maybe the whole request options? This _could_ also deprecate the `proxy` option which could be recreated when the whole request options would be configurable.

**Comment by jucrouzet** [comment]
Maybe making the whole requestOptions configurable would be lighter and more flexible. @vvo / @stephenash ?

**Comment by vvo** [comment]
Yep we should make it so that anyone can pass requestOptions via programmatic API

**Comment by vvo** [comment]
And explain in README those edge cases

**Comment by donaldpipowitch** [comment]
Updated 👍

**Comment by vvo** [comment]
Thanks, perfect

**Pull request merged**
