### PR TITLE
Update for lastest version of Selenium, Firefox and Chrome

### PR DESCRIPTION
**Pull request by geskill**

### CODE REVIEW

**Comment by vvo** [comment]
Tests are failing, unsure if this is new or not

**Comment by geskill** [comment]
The geckodriver Team did not upload a 32 bit version of v0.19.0 - strange (maybe forget this or deprecated this cause ff default is now 64 bit)
https://github.com/mozilla/geckodriver/releases

**Comment by chanjsq** [comment]
Hi, any progress on this PR?

**Comment by vvo** [comment]
@chanjsq seems like tests are failing because gecko driver could not be downloaded, no idea why

**Comment by vvo** [comment]
Figure it out and let's merge this, but I can't dig this right now

**Comment by laoshu133** [comment]
Geckodriver having problems with the Travis builder.

Follow this issue: https://github.com/mozilla/geckodriver/issues/951

**Comment by chanjsq** [comment]
@laoshu133 Thank you.

**Comment by chanjsq** [comment]
@vvo win32 uploaded https://github.com/mozilla/geckodriver/issues/951 😃

**Comment by usmonster** [comment]
Hi @geskill! Thanks for this update—I was about to make another very similar PR just to update ChromeDriver. Would you mind instead simply updating your PR to bump it to version 2.33 before merging?

**Comment by geskill** [comment]
@usmonster done. but i am not in the ability to merge this.
@vvo please merge this. build is passing now since the geckodriver Team did upload a correct 32 bit version. Thanks!

**Comment by vvo** [comment]
awesome work!

**Pull request merged**
